{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-9.3.1.jar",
          "url": "gradle-api-9.3.1.jar",
          "size": 413599,
          "sha512": "d34f00f9f740f2137c3ed937dcfcc3850836c67f472c9896cd2c75e31ac31f3aec013dd213d9487a0f11399448aa40acaba2ede8624279f77e92c3b8e3750b14",
          "sha256": "22fe12b730c9125a834a8d00c78453ce1f94b5388331e3d31d78409d7298812d",
          "sha1": "6a2bae5151369bab782efd2beb237f28b757ac8d",
          "md5": "56650b8b6ade136d7f7e200c2af344c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "9.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-9.3.1.jar",
          "url": "gradle-api-9.3.1.jar",
          "size": 413599,
          "sha512": "d34f00f9f740f2137c3ed937dcfcc3850836c67f472c9896cd2c75e31ac31f3aec013dd213d9487a0f11399448aa40acaba2ede8624279f77e92c3b8e3750b14",
          "sha256": "22fe12b730c9125a834a8d00c78453ce1f94b5388331e3d31d78409d7298812d",
          "sha1": "6a2bae5151369bab782efd2beb237f28b757ac8d",
          "md5": "56650b8b6ade136d7f7e200c2af344c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-9.3.1-javadoc.jar",
          "url": "gradle-api-9.3.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-9.3.1-sources.jar",
          "url": "gradle-api-9.3.1-sources.jar",
          "size": 385642,
          "sha512": "a997f0b5988bd2e9d1da89eab0612924fa306ed20b8a9e0ac3cbeef778f6bf7b58015816de3b5a3aaf2d594b76f0c06dfd7f19f6f48b8796d59f8a502864018b",
          "sha256": "f6bb5c976426836f1bd25b04a1d7bfde32d8dfc4d681ff38b86dfb6160e2790b",
          "sha1": "4d3be9e007e399776bacd3dcffc74d57d04e90f1",
          "md5": "722cf158f1791654e0033629ed62f1c4"
        }
      ]
    }
  ]
}
