{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "9.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-9.3.1.jar",
          "url": "gradle-9.3.1.jar",
          "size": 13156012,
          "sha512": "13d9c598f2f446fbbb305af58ee7c3ee13df69ef4a5a1eadfc792bed2964f470da9c76f83847e92eac5ddf2fa9495cd3e41f54c168232a6f92fff6530e581f03",
          "sha256": "4ae9f55cef115978de7f502e49ea163e89c78a8ab40943504a37c948b94eadb5",
          "sha1": "c1b6c02a8fc39bf66416535fb07a966f2a0aea86",
          "md5": "65cbbbf42d3c25ee7a0b29d04ed79690"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-settings-api",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "9.3.1-15703166"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aaptcompiler",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "crash",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-typedef-remover",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "gradle-work-action-api",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "bundletool",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-processor",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-metadata",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "9.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "2.2.10-2.0.2"
          },
          "reason": "KSP version needs to match KGP version"
        }
      ],
      "files": [
        {
          "name": "gradle-9.3.1.jar",
          "url": "gradle-9.3.1.jar",
          "size": 13156012,
          "sha512": "13d9c598f2f446fbbb305af58ee7c3ee13df69ef4a5a1eadfc792bed2964f470da9c76f83847e92eac5ddf2fa9495cd3e41f54c168232a6f92fff6530e581f03",
          "sha256": "4ae9f55cef115978de7f502e49ea163e89c78a8ab40943504a37c948b94eadb5",
          "sha1": "c1b6c02a8fc39bf66416535fb07a966f2a0aea86",
          "md5": "65cbbbf42d3c25ee7a0b29d04ed79690"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-9.3.1-javadoc.jar",
          "url": "gradle-9.3.1-javadoc.jar",
          "size": 629635,
          "sha512": "0976aea3e5c4135b5daeb668f5c52c7a6a4bdc6dd3b57c0f32eb1c9def51a7091bdd85119c62c83ed1bce0b58101cc42e982aa0390a049b18597c8a97c2ab5da",
          "sha256": "1596056fc8e98fea531d28b99bbc9f4dc2b93cd48f22c2dba9485d50be065833",
          "sha1": "37d3caae7c4e1013c45a2775695f0d63a2f31fcb",
          "md5": "6589fc6d2c5c898b6b689bdcbe48361d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-9.3.1-sources.jar",
          "url": "gradle-9.3.1-sources.jar",
          "size": 3946786,
          "sha512": "096ef4b3713f44f41d4c37f3731341ced2ca08034dd7d46f84a7c455a2ebcb8a977afc9c6ed5cbb5e0db7f792e3a409ddd90c3f0046c57d0fda1def755b5051c",
          "sha256": "f59c3f650bb7bf558c8757dd1bec7d202f358baa222239e5402f0294be0774c7",
          "sha1": "e181de60a9e42ee7383a84ba2f48a08027f170b2",
          "md5": "a2328e410f6e2902402d93656f55cc47"
        }
      ]
    }
  ]
}
