{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-9.3.1.jar",
          "url": "builder-model-9.3.1.jar",
          "size": 143245,
          "sha512": "2dc49a607ea14de5dae646328235c0bac967f8d09186773860070f73ebcd73a024d8a79d65f73689075eb5e7e2f60fe7c9abcc059aed75d668f80910f2303136",
          "sha256": "f1da398dd40d289ae566022b057c7ce7bd93b60d0d747f9938db645f0c872bfc",
          "sha1": "fe12e17bfff4c64eb827dbf9f697d1b7477f43cd",
          "md5": "3ce0602dca28bee9025a4a79aed362c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "32.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-9.3.1.jar",
          "url": "builder-model-9.3.1.jar",
          "size": 143245,
          "sha512": "2dc49a607ea14de5dae646328235c0bac967f8d09186773860070f73ebcd73a024d8a79d65f73689075eb5e7e2f60fe7c9abcc059aed75d668f80910f2303136",
          "sha256": "f1da398dd40d289ae566022b057c7ce7bd93b60d0d747f9938db645f0c872bfc",
          "sha1": "fe12e17bfff4c64eb827dbf9f697d1b7477f43cd",
          "md5": "3ce0602dca28bee9025a4a79aed362c2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-9.3.1-javadoc.jar",
          "url": "builder-model-9.3.1-javadoc.jar",
          "size": 265035,
          "sha512": "fa699a2e5957bb1a04b14210533112d3b60eff4a6e6e5d6bad5eb47f098f417456667dec7fe8bd13f8f4a5091895eb4ee84aea1d662301228979e91873e5a7ed",
          "sha256": "1542a35bd8dd053fdb9f546725c9fb4f000fdc6159255794ca30fba9e69f8ab4",
          "sha1": "eab774a3c02fc4134412cb9e1e42989f5a044117",
          "md5": "b9ed1e6ad80cd12a6d2cfcf3d34451a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-9.3.1-sources.jar",
          "url": "builder-model-9.3.1-sources.jar",
          "size": 153519,
          "sha512": "ad6b3485f9364889c5d3dc92f7930267fb4e9310330c5e12db13c0acb92115e83524cfa067ce88cf1e0f2a7741317a02a615487e5c95c7178d16ade19582b29c",
          "sha256": "b8079063f7c0592778f8b9442e9a902192f5fba709ac207c2875a9a708927286",
          "sha1": "189f1ee7f839ffdfab8faa0b1826a84811e91337",
          "md5": "5c2b124af512464bb20efa256fb8eb4d"
        }
      ]
    }
  ]
}
